---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  apt: name=ntpdate state=present

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf

- name: Start the ntp service
  service: name=ntpdate state=started enabled=yes
